FROM mdillon/postgis:11-alpine

LABEL maintainer="Thomas Piller <thomas.piller@unepgrid.ch>"

VOLUME /shared

COPY ./init/ /docker-entrypoint-initdb.d/

RUN chown -R postgres:root /docker-entrypoint-initdb.d/sql_files

