import { describe, expect, it } from "vitest";
import {
  buildAreaOverlapSql,
  buildCreateOverlapSql,
  buildFinalizeOverlapSql,
  buildOverlapGeometryProfileSql,
  deriveOverlapGeometryType,
} from "./sql.js";

const base = "mx_vector_a_b_c_d_e";
const mask = "mx_vector_f_g_h_i_j";
const output = "mx_vector_k_l_m_n_o";

describe("overlap SQL", () => {
  it("groups intersection fragments by the base gid", () => {
    const sql = buildCreateOverlapSql({
      idSource: output,
      layers: [base, mask],
      attributes: ["name", "year"],
    });

    expect(sql).toContain('CREATE TABLE "mx_vector_k_l_m_n_o"');
    expect(sql).toContain("GROUP BY gid");
    expect(sql).toContain("ST_UnaryUnion(ST_Collect(geom))");
    expect(sql).toContain('SELECT base.gid, "name", "year"');
    expect(sql).not.toContain("ST_CollectionExtract(");
    expect(sql).toContain("$1");
    expect(sql).not.toContain("_mx_valid");
  });

  it("profiles actual intersection dimensions without discarding components", () => {
    const sql = buildOverlapGeometryProfileSql({ idSource: output });

    expect(sql).toContain("ST_Dump(geom)");
    expect(sql).toContain("DISTINCT ST_Dimension(part.geom)");
    expect(sql).toContain('"mx_vector_k_l_m_n_o"');
  });

  it.each([
    [[0], "POINT"],
    [[1], "LINESTRING"],
    [[2], "POLYGON"],
    [[0, 1], "GEOMETRY"],
    [[1, 2], "GEOMETRY"],
    [[0, 1, 2], "GEOMETRY"],
    [[], "GEOMETRY"],
  ])("derives output type from dimensions %j", (dimensions, expected) => {
    expect(deriveOverlapGeometryType(dimensions)).toBe(expected);
  });

  it("calculates polygonal area in PostGIS", () => {
    const sql = buildAreaOverlapSql({ layers: [base, mask] });

    expect(sql).toContain("ST_Area(");
    expect(sql).toContain("::geography");
    expect(sql).toContain("ST_CollectionExtract(");
    expect(sql).toContain('"mx_vector_a_b_c_d_e"');
    expect(sql).toContain('"mx_vector_f_g_h_i_j"');
  });

  it("finalizes geometry and gid as multipart identity columns", () => {
    const statements = buildFinalizeOverlapSql({
      idSource: output,
      geometryType: "POLYGON",
      srid: 4326,
    }).join("\n");

    expect(statements).toContain("geometry(MULTIPOLYGON, 4326)");
    expect(statements).toContain("GENERATED BY DEFAULT AS IDENTITY");
    expect(statements).toContain("setval(");
    expect(statements).toContain("PRIMARY KEY (gid)");
  });

  it("keeps mixed geometry output generic while promoting each value", () => {
    const create = buildCreateOverlapSql({
      idSource: output,
      layers: [base],
      attributes: [],
    });
    const finalize = buildFinalizeOverlapSql({
      idSource: output,
      geometryType: "GEOMETRY",
      srid: 4326,
    }).join("\n");

    expect(create).not.toContain("ST_CollectionExtract(");
    expect(finalize).toContain("geometry(GEOMETRY, 4326)");
    expect(finalize).toContain("ST_Multi(geom)");
  });

  it("rejects unsafe identifiers", () => {
    expect(() =>
      buildCreateOverlapSql({
        idSource: output,
        layers: [base],
        attributes: ['name"; DROP TABLE mx_sources; --'],
        dimension: 3,
      }),
    ).toThrow("Invalid SQL identifier");
  });
});
