-- initial tables
REVOKE ALL PRIVILEGES ON mx_config FROM mapxc CASCADE;
REVOKE ALL PRIVILEGES ON mx_logs FROM mapxc CASCADE;
REVOKE ALL PRIVILEGES ON mx_projects FROM mapxc CASCADE;
REVOKE ALL PRIVILEGES ON mx_sources FROM mapxc CASCADE;
REVOKE ALL PRIVILEGES ON mx_users FROM mapxc CASCADE;
REVOKE ALL PRIVILEGES ON mx_views FROM mapxc CASCADE;
REVOKE ALL PRIVILEGES ON mx_views_latest FROM mapxc CASCADE;

-- tables added via the migration system
REVOKE ALL PRIVILEGES ON mx_countries FROM mapxc CASCADE;
REVOKE ALL PRIVILEGES ON mx_dict_translate FROM mapxc CASCADE;
REVOKE ALL PRIVILEGES ON mx_gemet FROM mapxc CASCADE;
REVOKE ALL PRIVILEGES ON mx_patches FROM mapxc CASCADE;
