/*jshint esversion: 6 */
import * as mx from './mx_init.js';

$(document).on('shiny:connected', function(event) {

  /*
  * Input
  */
  Shiny.onInputChange('cookies', mx.helpers.readCookie());

  /*
  * Output
  */

  Shiny.addCustomMessageHandler("mxSetCookie",mx.helpers.writeCookie);
  Shiny.addCustomMessageHandler('mxModal', mx.helpers.modal);
  Shiny.addCustomMessageHandler('mxSetTemplates', mx.helpers.setTemplates);
  Shiny.addCustomMessageHandler('mxSetElementAttribute', mx.helpers.setElementAttribute);
  Shiny.addCustomMessageHandler("mxSetImageAttributes", mx.helpers.setImageAttributes);
  Shiny.addCustomMessageHandler("mxUiHide", mx.helpers.hide);
  Shiny.addCustomMessageHandler("mxUpdateText", mx.helpers.updateText);
  Shiny.addCustomMessageHandler("mxJsDebugMsg", mx.helpers.jsDebugMsg);
  Shiny.addCustomMessageHandler("mxButtonToggle", mx.helpers.buttonToggle);
  Shiny.addCustomMessageHandler("mxSetLanguage", mx.helpers.setLanguage);
  Shiny.addCustomMessageHandler("mxJsonToObj", mx.helpers.jsonToObj);
  Shiny.addCustomMessageHandler("mxProgress",mx.helpers.progressScreen);
  Shiny.addCustomMessageHandler("mxInjectHead",mx.helpers.injectHead);
  Shiny.addCustomMessageHandler("mxUpdateSelectizeItems",mx.helpers.updateSelectizeItems);
  Shiny.addCustomMessageHandler('mglInit', mx.helpers.initMap );// mapbox gl init
  Shiny.addCustomMessageHandler('mglSetLanguage', mx.helpers.setMapLanguage ); // Set country language
  //Shiny.addCustomMessageHandler('mglSaveViewsList', mx.helpers.saveViewsList ); // Save update vuew list
  Shiny.addCustomMessageHandler('mglRenderViewsList', mx.helpers.renderViewsList ); // Render view list to ui
  //Shiny.addCustomMessageHandler('mglAddAutoLayer', mx.helpers.addAutoLayer );// add auto layer generated by schema
  //Shiny.addCustomMessageHandler('mglAddStyle', mx.helpers.addStyle );// add view style
  //Shiny.addCustomMessageHandler('mglAddSources', mx.helpers.addSources );// add sources
  Shiny.addCustomMessageHandler('mglSetFilter', mx.helpers.setFilter );// filter visible feature of the given layer id
  Shiny.addCustomMessageHandler('mglAddLayer',  mx.helpers.addLayer );// add new layer
  Shiny.addCustomMessageHandler('mglFlyTo', mx.helpers.flyTo );// go to location with animation
  Shiny.addCustomMessageHandler('mglSyncAllMaps', mx.helpers.syncAll );// sync all maps


});





