/*jshint esversion: 6 */

$(document).on('shiny:connected', function(event) {
  // add auto layer generated by schema
  Shiny.addCustomMessageHandler('jedInit', function(e) {
    jed.helper.render(e.id,e.schema,e.startVal,e.options);
  });
  // update editor with given values
  Shiny.addCustomMessageHandler('jedUpdate', function(e) {
    jed.helper.update(e.id,e.val);
  });
});



