\set read_pwd `echo "$POSTGRES_USER_READ_PASSWORD"`
\set write_pwd `echo "$POSTGRES_USER_WRITE_PASSWORD"`
\set custom_pwd `echo "$POSTGRES_USER_CUSTOM_PASSWORD"`

--
-- Roles read/write
--

CREATE ROLE readonly;
ALTER ROLE readonly WITH 
NOSUPERUSER 
INHERIT 
NOCREATEROLE 
NOCREATEDB 
NOLOGIN 
NOREPLICATION
NOBYPASSRLS;

CREATE ROLE readwrite;
ALTER ROLE readwrite WITH 
NOSUPERUSER 
INHERIT 
NOCREATEROLE 
NOCREATEDB 
NOLOGIN 
NOREPLICATION 
NOBYPASSRLS;

--
--  Mapx roles
--
CREATE ROLE mapxw;
ALTER ROLE mapxw WITH 
LOGIN 
PASSWORD :'write_pwd';

CREATE ROLE mapxr;
ALTER ROLE mapxr WITH
LOGIN 
PASSWORD :'read_pwd';

CREATE ROLE mapxc;
ALTER ROLE mapxc
WITH 
LOGIN 
PASSWORD :'custom_pwd';

GRANT USAGE ON SCHEMA public TO readonly;
GRANT USAGE ON SCHEMA public TO readwrite;
ALTER DEFAULT PRIVILEGES FOR USER mapxw IN SCHEMA public GRANT SELECT ON TABLES TO readonly;

GRANT readwrite TO mapxw;
GRANT readonly TO mapxr;
GRANT readonly TO mapxc;


