\set read_pwd `echo "$POSTGRES_USER_READ_PASSWORD"`
\set write_pwd `echo "$POSTGRES_USER_WRITE_PASSWORD"`
\set custom_pwd `echo "$POSTGRES_USER_CUSTOM_PASSWORD"`

--
-- Roles
--


CREATE ROLE mapxr;
ALTER ROLE mapxr WITH
NOSUPERUSER 
INHERIT 
NOCREATEROLE 
NOCREATEDB 
LOGIN 
NOREPLICATION 
NOBYPASSRLS 
PASSWORD :'read_pwd';

CREATE ROLE mapxw;
ALTER ROLE mapxw WITH 
NOSUPERUSER 
INHERIT 
CREATEROLE 
NOCREATEDB 
LOGIN 
NOREPLICATION 
NOBYPASSRLS 
PASSWORD :'write_pwd';

CREATE ROLE mapxc;
ALTER ROLE mapxc
WITH 
NOSUPERUSER 
NOINHERIT 
NOCREATEROLE 
NOCREATEDB 
LOGIN 
NOREPLICATION 
NOBYPASSRLS 
PASSWORD :'custom_pwd';

CREATE ROLE readonly;
ALTER ROLE readonly WITH 
NOSUPERUSER 
INHERIT 
NOCREATEROLE 
NOCREATEDB 
NOLOGIN 
NOREPLICATION
NOBYPASSRLS;

CREATE ROLE readwrite;
ALTER ROLE readwrite WITH 
NOSUPERUSER 
INHERIT 
NOCREATEROLE 
NOCREATEDB 
NOLOGIN 
NOREPLICATION 
NOBYPASSRLS;

--
-- Role memberships
--
GRANT readonly TO mapxr GRANTED BY postgres;
GRANT readwrite TO mapxw GRANTED BY postgres;

--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: pguser
--

GRANT USAGE ON SCHEMA public TO mapxc;
GRANT USAGE ON SCHEMA public TO readonly;
GRANT USAGE ON SCHEMA public TO readwrite;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: -; Owner: mapxw
--

ALTER DEFAULT PRIVILEGES FOR ROLE mapxw GRANT SELECT ON TABLES  TO readonly;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: mapxw
--

ALTER DEFAULT PRIVILEGES FOR ROLE mapxw IN SCHEMA public GRANT SELECT ON TABLES TO mapxc;
