\set read_pwd `echo "$POSTGRES_USER_READ_PASSWORD"`
\set write_pwd `echo "$POSTGRES_USER_WRITE_PASSWORD"`
\set custom_pwd `echo "$POSTGRES_USER_CUSTOM_PASSWORD"`

--
-- Roles
--


CREATE ROLE mapxr;
ALTER ROLE mapxr WITH
NOSUPERUSER 
INHERIT 
NOCREATEROLE 
NOCREATEDB 
LOGIN 
NOREPLICATION 
NOBYPASSRLS 
PASSWORD :'read_pwd';

CREATE ROLE mapxw;
ALTER ROLE mapxw WITH 
NOSUPERUSER 
INHERIT 
CREATEROLE 
NOCREATEDB 
LOGIN 
NOREPLICATION 
NOBYPASSRLS 
PASSWORD :'write_pwd';

CREATE ROLE mapxc;
ALTER ROLE mapxc
WITH 
NOSUPERUSER 
NOINHERIT 
NOCREATEROLE 
NOCREATEDB 
LOGIN 
NOREPLICATION 
NOBYPASSRLS 
PASSWORD :'custom_pwd';

CREATE ROLE readonly;
ALTER ROLE readonly WITH 
NOSUPERUSER 
INHERIT 
NOCREATEROLE 
NOCREATEDB 
NOLOGIN 
NOREPLICATION
NOBYPASSRLS;

CREATE ROLE readwrite;
ALTER ROLE readwrite WITH 
NOSUPERUSER 
INHERIT 
NOCREATEROLE 
NOCREATEDB 
NOLOGIN 
NOREPLICATION 
NOBYPASSRLS;

--
-- Role memberships
--
GRANT readonly TO mapxr GRANTED BY postgres;
GRANT readwrite TO mapxw GRANTED BY postgres;


