/**
 * Types, should matches "app/src/js/handsontable/types.js"
 */
export const pgTypesData = [
  // Basic types
  "jsonb",
  "boolean",
  "bigint",
  "double precision",
  "integer",
  "numeric",
  "real",
  "smallint",
  "text",
  "date",
  "character varying",
  "time with time zone",
  "time without time zone",
  "timestamp with time zone",
  "timestamp without time zone",

  // Array types - commonly used by GDAL/PostGIS
  "jsonb[]",
  "boolean[]",
  "bigint[]",
  "double precision[]",
  "integer[]",
  "numeric[]",
  "real[]",
  "smallint[]",
  "text[]",
  "date[]",
  "character varying[]",
  "time with time zone[]",
  "time without time zone[]",
  "timestamp with time zone[]",
  "timestamp without time zone[]",

  // Additional PostGIS/GDAL specific types
  "uuid",
  "uuid[]",
  "bytea",
  "bytea[]",
  "inet",
  "inet[]",
  "json",
  "json[]",
  "xml",
  "xml[]",

  // PostGIS geometry types (commonly used with GDAL)
  "geometry",
  "geometry[]",
  "geography",
  "geography[]",
  "point",
  "point[]",
  "linestring",
  "linestring[]",
  "polygon",
  "polygon[]",
  "multipoint",
  "multipoint[]",
  "multilinestring",
  "multilinestring[]",
  "multipolygon",
  "multipolygon[]",
  "geometrycollection",
  "geometrycollection[]",
];
